"""add_daily_lessons_table

Revision ID: 087e63bd8f2d
Revises: eb9632fbecac
Create Date: 2025-09-18 09:31:58.453356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087e63bd8f2d'
down_revision: Union[str, None] = 'eb9632fbecac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('daily_tip', sa.JSON(), nullable=False),
    sa.Column('swipe_cards', sa.JSON(), nullable=False),
    sa.Column('scenario', sa.JSON(), nullable=False),
    sa.Column('go_deeper', sa.JSON(), nullable=False),
    sa.Column('reflection_prompt', sa.Text(), nullable=False),
    sa.Column('leader_win', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_lessons_id'), 'daily_lessons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_lessons_id'), table_name='daily_lessons')
    op.drop_table('daily_lessons')
    # ### end Alembic commands ###
