"""make journey fields nullable

Revision ID: 190bbebf8439
Revises: 160b533058e7
Create Date: 2025-10-01 11:52:08.984515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190bbebf8439'
down_revision: Union[str, None] = '160b533058e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_journeys', 'growth_focus_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_journeys', 'intentional_advantage_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_journeys', 'intentional_advantage_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_journeys', 'growth_focus_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
