"""Add categories_completed array to user_journeys

Revision ID: 4d5e6eca12c6
Revises: 4d9e58619a1b
Create Date: 2025-09-30 13:19:14.548389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5e6eca12c6'
down_revision: Union[str, None] = '4d9e58619a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_journeys', sa.Column('categories_completed', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_journeys', 'categories_completed')
    # ### end Alembic commands ###
