"""Add role request fields for approval workflow

Revision ID: 793e0436f3dc
Revises: bda478a70aef
Create Date: 2025-09-09 17:25:33.890026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793e0436f3dc'
down_revision: Union[str, None] = 'bda478a70aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type for role request status
    rolerequeststatus_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='rolerequeststatus')
    rolerequeststatus_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('requested_role', sa.Enum('PARTICIPANT', 'COACH', 'ADMIN', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('role_request_status', rolerequeststatus_enum, nullable=True))
    op.add_column('users', sa.Column('role_request_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('role_approved_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role_approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_approved_at')
    op.drop_column('users', 'role_approved_by')
    op.drop_column('users', 'role_requested_at')
    op.drop_column('users', 'role_request_reason')
    op.drop_column('users', 'role_request_status')
    op.drop_column('users', 'requested_role')
    # Drop the enum type
    sa.Enum(name='rolerequeststatus').drop(op.get_bind())
    # ### end Alembic commands ###
