"""Add user roles and email verification

Revision ID: bda478a70aef
Revises: ced0ce98d2bd
Create Date: 2025-09-09 17:17:23.999957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda478a70aef'
down_revision: Union[str, None] = 'ced0ce98d2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    userrole_enum = sa.Enum('PARTICIPANT', 'COACH', 'ADMIN', name='userrole')
    userrole_enum.create(op.get_bind())
    
    # Add columns with default values
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='PARTICIPANT'))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'role')
    # Drop the enum type
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
